---
- name: multiply users
  hosts: webserver[0]
  become: yes

  tasks:
    - name: users only in one node
      user: name= "{{ item }}" state=present
      with_items:
        - raj
        - hari
        - saidemy
        - harsha




