---
- name: variables 
  hosts: all
  become: yes
  
  vars:
    tomcat: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.33/bin/apache-tomcat-10.1.33.tar.gz


  tasks: 
  - name: install java
    yum:
      name: java
      state: install
  when: anible_os_family == "RedHat"

  - name: download tomcat
  get_url:
    url: tomcat
    dest: /opt
  
  - name: extracting tom floder
    unarchive:
     src: /opt/apache-tomcat-10.1.33.tar.gz
     dest: /opt/tomcat

     #service start in another playbook

  
